
version: '2'
services:

  nginx:
    build: ./nginx/
    image: nginx-img:0.0.1
    container_name: nginx
    hostname: nginx
    depends_on:
        - php.fpm
    networks:
        - web_vlan
    volumes:
        - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/conf/conf.d/:/etc/nginx/conf.d/
        - ./nginx/conf/fastcgi.conf:/etc/nginx/fastcgi.conf
        - ./www:/www
        - ./ssl/:/etc/nginx/ssl/
        - ./logs:/var/log/nginx
        - "phpsocket:/var/run"
    restart: always
    ports:
        - 10080:80
        - 10443:443

  php.fpm:
    build: ./php-fpm/
    image: php.fpm-img:0.0.1
    container_name: php.fpm
    hostname: php.fpm
    networks:
        - web_vlan
    volumes:
        - ./php-fpm/conf:/usr/local/etc/php-fpm.d
        - ./php-fpm/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        - ./www:/www
        - "phpsocket:/var/run"
    restart: always

networks:
  web_vlan:

volumes:
  phpsocket:
